services:
  joiblogdb:
    image: mongo:latest
    container_name: joiblogdb
    hostname: joiblogdb
    volumes:
      - joiblogdb-data:/data/db/
      - joiblogdb-log:/var/log/mongodb/
      - ./mongodb-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    env_file:
      - path: .env
        required: false
      - path: .env.development
        required: false
      - path: .env.development.local
        required: false
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
      - "27017:27017"
    networks:
      - joiblogdb_network

volumes:
  joiblogdb-data:
    driver: local
    name: joiblogdb-data
  joiblogdb-log:
    driver: local
    name: joiblogdb-log

networks:
  joiblogdb_network:
    driver: bridge
    name: joiblogdb-network